# Generated by Django 2.2 on 2021-03-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesvizionquestions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='examDate',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='examVersion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
